layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # youtube: your_username
  twitter: _tsub_
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Kubernetes
    web_url: https://kubernetes.io
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/6ec5a7d3371729a6d922f66ad8703de5e3d6ac95/logo/logo.png

  - name: Golang
    web_url: https://golang.org
    image_url: https://user-images.githubusercontent.com/10208211/54131468-c0db0980-4455-11e9-8b4b-a766ca97088b.png

  - name: Terrform
    web_url: https://terraform.io
    image_url: https://www.terraform.io/assets/images/og-image-8b3e4f7d.png
